services:
  apk:
    build: .
    container_name: website
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mangos

  mangos:
    image: mongo:latest
    container_name: database
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apk

  

  

  
